# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/calo/300_time_frames/val_data_joint_upper_middle.npy
  label_path: ./data/calo/300_time_frames/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 11
  num_point: 14
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  seg: 1
  graph: graph.calo.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 32
weights: ./pretrained_models/upper_best.pth


work_dir: ./eval/calo/upper_middle
save_score: True
metric: upper