base_lr: 0.05
batch_size: 2
case: 0
config: config/calo/train_upper_middle.yaml
dataset: calo
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
graph: calo
ignore_weights: []
log_interval: 100
metric: upper
model: model.calo
model_args:
  graph: graph.calo.AdjMatrixGraph
  num_class: 11
  num_g3d_scales: 6
  num_gcn_scales: 13
  num_person: 1
  num_point: 14
  seg: 1
model_saved_name: ''
monitor: val_acc
nesterov: true
num_epoch: 100
num_worker: 0
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: true
seed: 1
seg: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 32
test_feeder_args:
  data_path: ./data/calo/val_data_joint_upper_middle.npy
  label_path: ./data/calo/val_label.pkl
train: 1
train_feeder_args:
  data_path: ./data/calo/train_data_joint_upper_middle.npy
  debug: false
  label_path: ./data/calo/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/calo
workers: 0
