# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu_light/xsub/val_data_joint_upper_middle.npy
  label_path: ./data/ntu_light/xsub/val_label.pkl
  debug: False

# model
model: model.semantic_shift.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
#  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
#  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  seg: 1

# test
phase: test
device: [0]
test_batch_size: 1
weights: ./pretrained_models/weights-16-20032.pt
#weights: ./pretrained_models/ntu_ShiftGCN_joint_xsub.pt

work_dir: ./eval/ntu_light/xsub/upper/
save_score: True