assume_yes: false
base_lr: 0.05
batch_size: 1
case: 0
checkpoint: null
config: ./config/nturgbd-cross-subject/train.yaml
dataset: ntu_light
debug: false
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
forward_batch_size: 1
graph: calo
ignore_weights: []
log_interval: 100
metric: upper
model: model.semantic_shift.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
  seg: 1
model_saved_name: ''
monitor: acc_val
nesterov: true
num_epoch: 1
num_worker: 8
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: true
seed: 1
seg: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 1
test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
train: 1
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_joint.npy
  debug: false
  label_path: ./data/ntu/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/ntu/xsub/upper
workers: 0
