assume_yes: false
base_lr: 0.01
batch_size: 256
case: 0
checkpoint: null
config: ./config/nturgbd-cross-subject/test_upper_joint.yaml
dataset: ntu
debug: false
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
forward_batch_size: 1
graph: calo
ignore_weights: []
log_interval: 100
model: model.semantic_shift.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
  seg: 1
model_saved_name: ''
monitor: acc_val
nesterov: false
num_epoch: 80
num_worker: 8
only_train_epoch: 0
only_train_part: false
optimizer: SGD
part: upper
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
seg: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 1
test_feeder_args:
  data_path: ./data/ntu_light/xsub/val_data_joint_upper_middle.npy
  debug: false
  label_path: ./data/ntu_light/xsub/val_label.pkl
train: 1
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: ./pretrained_models/weights-16-20032.pt
work_dir: ./eval/ntu_light/xsub/upper/
workers: 0
