Experiment_name: calo_ShiftGCN_joint
base_lr: 0.1
batch_size: 32
config: ./config/calo/train_joint.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.shift_gcn.Model
model_args:
  graph: graph.calo.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 11
  num_person: 1
  num_point: 18
model_saved_name: ./save_models/calo_ShiftGCN_joint
nesterov: true
num_epoch: 100
num_worker: 32
only_train_epoch: 1
only_train_part: true
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 60
- 80
- 100
test_batch_size: 32
test_feeder_args:
  data_path: ./data/calo/test_data_joint.npy
  label_path: ./data/calo/test_label.pkl
train_feeder_args:
  data_path: ./data/calo/train_data_joint.npy
  debug: false
  label_path: ./data/calo/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/calo_ShiftGCN_joint
